#-------------------------------
# General Site Settings
baseURL = "http://example.org/"
languageCode = "en-us"
title = "Norlin"
googleAnalytics = "" # Add your identifier. For example UA-99631805-1.
paginate = 8


#-------------------------------
# Main Menu
[menu]
  [[menu.main]]
    name = "Home"
    url = "/"
    weight = 1

  [[menu.main]]
    name = "About"
    url = "/about"
    weight = 2

  [[menu.main]]
    name = "Contact Me"
    url = "/contact"
    weight = 3

  [[menu.main]]
    name = "Style Guide"
    url = "/styleguide"
    weight = 4


[params]
  logo = "" # You can add own logo. For example "/images/logo.png".
  description = "Norlin – A Beautiful Dark Blog Theme for Hugo."

  [params.author]
    name = "Robert Wilson"
    avatar = "/images/15.jpg"

  #-------------------------------
  # Hero Settings
  [params.hero]
    hero__title = "Robert Wilson"
    hero__description = "Thoughts, stories and ideas."
    hero__image = "/images/01.jpg"

  [[params.social]]
    icon = "fa-brands fa-x-twitter"
    name = "Twitter"
    link = "https://twitter.com"

  [[params.social]]
    icon = "fa-brands fa-facebook-f"
    name = "Facebook"
    link = "https://facebook.com"

  [[params.social]]
    icon = "fa-brands fa-dribbble"
    name = "Dribbble"
    link = "https://dribbble.com"

  [[params.social]]
    icon = "fa-brands fa-instagram"
    name = "Instagram"
    link = "https://instagram.com"

  [[params.social]]
    icon = "fa-brands fa-pinterest"
    name = "Pinterest"
    link = "https://pinterest.com"

  [[params.social]]
    icon = "fa-brands fa-youtube"
    name = "Youtube"
    link = "https://youtube.com"

  [[params.social]]
    icon = "fa-brands fa-github"
    name = "Github"
    link = "https://github.com/"

  [[params.social]]
    icon = "fa-brands fa-vimeo-v"
    name = "Vimeo"
    link = "https://vimeo.com"

  # Example of adding a new link to the footer:
  # [[params.social]]
  #   icon = "fa-brands fa-tiktok"
  #   name = "TikTok"
  #   link = "https://tiktok.com"

  # Other icons can be found at https://fontawesome.com/icons


  #-------------------------------
  # Newsletter (partials/footer-widgets/widget-subscribe.html)
  [params.mailchimp]
    mailchimp__title = "Get Interesting News"
    mailchimp__text = "Subscribe to our newsletter and we’ll send you the emails of latest posts."
    mailchimp__identifier = "gmail.us21.list-manage.com/subscribe/post?u=8aeb9c31a5c97a3a5f9ff2740&amp;id=0e31fd7793&amp" # Add your MailChimp form identifier. For example - gmail.us21.list-manage.com/subscribe/post?u=8aeb9c31a5c97a3a5f9ff2740&amp;id=0e31fd7793&amp
    mailchimp__button__text = "Join" # Add your button text


  #-------------------------------
  # Contact Settings
  [params.contact]
    email = "your@email.com" # Add your form_id

    # NOTE
    # Norlin comes with a built-in contact form, that you can use with Formspree service to handle up to 50 submissions per month for free. You could also easily switch to another contact form service if you want.


  #-------------------------------
  # Comment Section (Disqus)
  [params.disqus]
    disqusShortname = "anvod-studio-test" # add your shortname for Disqus Comment. For example anvod-studio-test


[related]
  includeNewer = true
  threshold = 85
  toLower = false

  [[related.indices]]
  name = "tags"
  weight = 80

  [[related.indices]]
  name = "keywords"
  weight = 40

  [[related.indices]]
  name = "date"
  weight = 10


[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true


[outputs]
  home = ["HTML", "RSS", "JSON"]


[markup.highlight]
  codeFences = true
  guessSyntax = true
  noClasses = false